2023-05-26 15:48:04 (connectionpool.py:1048) DEBUG    Starting new HTTPS connection (1): www.jianshu.com:443
2023-05-26 15:48:04 (connectionpool.py:546) DEBUG    https://www.jianshu.com:443 "GET / HTTP/1.1" 403 None
2023-05-26 15:48:04 (test_casedome.py:25 ) ERROR    main Exception: Traceback (most recent call last):
  File "C:\Users\Hasee\PycharmProjects\pythonProjectForWork\interfaceAutomationTest\case\test_casedome.py", line 22, in test_01
    assert 200 == result
AssertionError: assert 200 == 304